### ISSUE TITLE
grizzl-20130810.202.tar: Not found

### ISSUE THREAD

**Issue by aidylewis** [grizzl/fiplr#54]
```
M-x package-install RET fiplr RET
```

http://melpa.milkbox.net/packages/grizzl-20130810.202.tar: Not found

**Comment by fmartingr** [comment]
This happens to me from time to time with some packages, do `M-x package-list-packages RET` and install from there.
I'm assuming that it will also work with `M-x package-refresh-contents RET`.

**Comment by aidylewis** [comment]
Thanks
